name: CI

on:
  pull_request:

jobs:
  CI:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3

      - name: docker compose up
        run: |
          make start
      - name: ci-black
        run: |
          make ci-black